### ISSUE TITLE
awk -F ';' ne parse pas correctement declaration_avantages.csv

### ISSUE THREAD

**Issue by fmassot** [regardscitoyens/sunshine-data#3]
certaines lignes contiennent des colonnes avec "blabla ; blabla"

faudrait utiliser gawk -vFPAT='([^;]*)|(\"[^\"]+\")'

**Comment by boogheta** [comment]
ou utiliser un vrai outil pour manipuler des csv en lignes de commande genre csvkit ou autre ptet plutôt non? :p

**Comment by kerneis** [comment]
Sinon dans Debian il y a csvtool (qui semble moins complet que csvkit
toutefois).

**Comment by fmassot** [comment]
@boogheta :)))
thx @boogheta @kerneis je vais regarder csvkit et csvtool, je me méfie toujours de csvkit avec les gros fichiers mais tant qu'on a pas de merge à faire ça devrait passer

**Comment by kerneis** [comment]
> je me méfie toujours de csvkit avec les gros fichiers mais tant qu'on
> a pas de merge à faire ça devrait passer

En ce qui concerne csvtool en tout cas, il est monstrueusement
inefficace (il charge tout en mémoire d'abord), et en cas d'erreur, les
messages ne sont pas très informatifs. Mais sur des CSVs qui tiennent en
mémoire et bien formés, ça marche bien :-)

**Comment by boogheta** [comment]
Yes effectivement dès qu'on a un gros CSV, csvkit qui charge tout en ram devient problématique.
J'ai croisé Miller cet été sinon qui a l'air cool mais pas eu l'occsion de tester encore ni de vérifier s'il loadait lazy ou pas : https://github.com/johnkerl/miller

**Comment by kerneis** [comment]
"Miller is _streaming_: most operations need only a single record in
memory at a time, rather than ingesting all input before producing
any output."

**Comment by fmassot** [comment]
bon au final un petit script python ça passe bien : https://github.com/regardscitoyens/sunshine-data/blob/master/scripts/format_declaration_conventions.py
